# Generated by Django 3.1 on 2020-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HJO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='title',
            new_name='position',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=5500),
        ),
    ]
